# Dependencies
markdown:         rdiscount
highlighter:      pygments

# Permalinks
permalink:        pretty

# Server
source:           prototype
destination:      _proto_render
host:             0.0.0.0
port:             9001
baseurl:          /
url:
encoding:         UTF-8

# Custom vars
current_version:  0.0.1
